name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - php: '8.2'
          - php: '8.2'
            composerFlags: '--prefer-stable --prefer-lowest'
          - php: '8.3'
          - php: '8.4'
          - php: '8.5'

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP with composer v2
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
          coverage: none

      - name: Validate composer.json
        run: composer validate --no-check-lock

      - name: Install dependencies
        run: composer update ${{ matrix.composerFlags }} --no-interaction --prefer-dist

      - name: Tests
        run: vendor/bin/phpunit
